apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: podinfo
spec:  
  replicas: 1  
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: singleinstance
    spec:
      containers:
      - name: podinfo
        image: pascalnaber/podinfo:2
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
spec:
  ports:
    - port: 80
  selector:
    app: singleinstance
  type: LoadBalancer